# Generated by Django 4.1.3 on 2022-12-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracks',
            options={},
        ),
    ]
