# Generated by Django 4.1.3 on 2022-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_albums_options_tracks_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
